services:
  ncat:
    build: .
    # image: no-code-architects-toolkit-ncat:latest
    container_name: ncat
    env_file:
      - .env.custom.minio.n8n
    ports:
      - "18083:18083"
    volumes:
      - storage:/app/storage
      - logs:/app/logs
    restart: unless-stopped
    networks:
      - n8n_proxy-net

volumes:
  storage:
    driver: local
  logs:
    driver: local

networks:
  n8n_proxy-net:
    external: true